CMD_CHAR_EXISTS EQU 1
CMD_CHAR_READ EQU 2
CMD_CHAR_WRITE EQU 3
CMD_BLOCK_READ EQU 4
CMD_BLOCK_WRITE EQU 5
BIOS_PORT_CMD EQU 10H
BIOS_PORT_DATA EQU 11H

    ORG 0
    LXI D, MSG
    CALL WRITE_STR
    HLT

WRITE_STR:
    PUSH PSW
    PUSH H
LOOP0:    
    LDAX D
    CPI '$'
    JZ EXIT0
    MOV L,A
    MVI A, CMD_CHAR_WRITE
    OUT BIOS_PORT_CMD
    MOV A,L
    OUT BIOS_PORT_DATA
    INX D
    JMP LOOP0
EXIT0:
    POP H
    POP PSW
    RET

MSG:    db 'Hello World\n$'